ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080

db:
  mongo:
    user: "ruben"
    password: "zixelowe1"
    host: "personal.yycznyk.mongodb.net"
    port: 27017
    maxPoolSize: 20
    database:
      name: "CarApp"
  pinecone:
    apiKey: "71d7b543-c70f-471f-9ba1-9699d1b00091"
    host: "https://piezas-phx6o3c.svc.aped-4627-b74a.pinecone.io"


cohere:
  apiKey: "r2W7dzTlvwxjBFsKXedUVUm08X0RvjAVAHZfDcVX"


jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"


